---
создал заметку: 2024-07-22
tags:
  - Java
  - Exception
  - Trowable
---
```java
try {
	//код, который может выбросить исключение
} catch (ExceptionType exception) {
	//код, соответствующий этому исключению
} finally {
	//код, который будет выполнен в любом случае
}
```

```java
public static void main(String[] args) {
long start = System.currentTimeMillis();
	try {
		doSomething();
		return;
	} catch (NullPointerException e) {
		System.out.println("We caught " + e);
	} catch (ArrayIndexOutOfBoundsException e) {
		System.out.println("We caught array index exception");
	} finally {//выполняется всегда, когда есть блок try. Даже если там return
	long duration = System.currentTimeMillis() - start;
		System.out.println("Duration: " + duration + " ms");
	}
}

public static void doSomething() {


}
```

в **finally** можно записывать код закрытия файла, чтобы не дублировать. Или чтобы измерить время выполнения кода, а именно вычислять разницу между текущим временем и временем старта

В **catch**-блоке может быть указан только наследник класса **Trowable**.
Указать **checked**-исключение в блоке catch не получится, если в try-блоке не вызывается метод, который помечен словом **trows** с соответствующим checked-исключением

```java
try {
	doSomething();
} catch (IOException e) {//не скомпилируется, нужен trows

}
```

```java
try {
	doSomething();
} catch (IOException e) {//успешно скомпилируется

}

public static void doSomething() throws IOException{


}
```

#### Несколько catch-блоков
В этом случае возникшее исключение обрабатывается первым блоком, который соответствует данному исключению.
Соответствие определяется следующим образом: либо тип исключения в catch-блоке совпадает с типом выброшенного исключения, либо тип выброшенного исключения является наследником типа, указанного в catch-блоке.
Короче, сверху вниз.

#### Multi-catch-механизм
Сразу несколько типов исключений
```java
catch (NullPointerException | ArithmeticException e) {

}
```